const VALUES = {
  CAPTION_FIRSTNAME: "First Name",
  CAPTION_PLACEHOLDER_FIRSTNAME: "Enter First Name",
  CAPTION_LASTNAME: "Last Name",
  CAPTION_PLACEHOLDER_LASTNAME: "Enter Last Name",
  CAPTION_OCCUPATION: "Occupation",
  CAPTION_OCCUPATION_EMPLOYED: "Employed",
  CAPTION_OCCUPATION_BUSINESS: "Business",
  CAPTION_OCCUPATION_STUDENT: "Student",
  CAPTION_DOB: "Date of birth",
  CAPTION_STATUS: "Status",
  CAPTION_STATUS_ACTIVE: "Active",
  CAPTION_STATUS_INACTIVE: "Inactive",
  CAPTION_BIO: "Bio",
  CAPTION_PROFILEPICTURE: "Profile Picture",
  CAPTION_BUTTON_CREATE: "Create Customer",
  CAPTION_BUTTON_EDIT: "Edit",
  CAPTION_BUTTON_SHOW_CUSTOMERLIST: "Display Customer List",
  CAPTION_BUTTON_SHOW_CUSTOMERFORM: "Display Customer Form",
  CAPTION_BUTTON_EDIT: "Edit Customer",
};

export default VALUES;
